# Generated by Django 5.1.2 on 2024-10-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_rename_internship_application_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Job',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internships.job'),
            preserve_default=False,
        ),
    ]
