# Generated by Django 5.1.2 on 2024-11-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_student_academic_status_student_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='internship_end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internship_start_date',
        ),
    ]
