# Generated by Django 5.1.2 on 2024-11-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_remove_student_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
