# Generated by Django 5.1.3 on 2024-11-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
