# Generated by Django 5.1.2 on 2024-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0013_employer_logo_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
