# Generated by Django 5.1.2 on 2024-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0016_alter_student_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='logo',
            field=models.FileField(blank=True, default='images/default_profile.jpg', null=True, upload_to='logo/'),
        ),
    ]
