# Generated by Django 5.1.2 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_alter_student_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
