# Generated by Django 5.1.2 on 2024-11-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_alter_student_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='internship_title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='internship_type',
        ),
    ]
