# Generated by Django 5.1.3 on 2024-11-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_rename_job_title_job_internship_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
