# Generated by Django 5.1.2 on 2024-11-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_employer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
