# Generated by Django 5.1.2 on 2024-11-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0021_employer_contact_number_employer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
