# Generated by Django 5.1.2 on 2024-11-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0022_application_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_viewed',
        ),
    ]
