# Generated by Django 5.1.2 on 2024-11-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0024_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
