# Generated by Django 5.1.2 on 2024-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0025_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
