# Generated by Django 5.1.2 on 2024-11-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0026_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
