# Generated by Django 5.1.2 on 2024-11-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0027_application_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
