# Generated by Django 5.1.2 on 2024-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0029_remove_application_employer_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stipend_expectation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
